#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  executes todo,sh lsgp for you while with color on file changes."
  curcmd=`basename $0`
}

# I guess just call this mini-shortcut
cd `dirname "$TODO_FILE/"`
# echo `dirname "$TODO_FILE/"`
# drive pull -no-prompt=true $TODO_FILE
# $TODO_FULL_SH lsgp
# doon "$TODO_FULL_SH lsgp" "drive push -no-prompt=true $todo_file"


echo "Commented because of missing dependencies"
