#!/usr/bin/env perl

my $history = ".history";
open (HIST, '<', $history) or die "cannot read $history: $!";
my @oldhist = <HIST>;
close HIST;

my @newhist = ();
my %seen = ();
while (my $cmd = pop @oldhist) {
	($s1, $s2) = split(/:0;/,$cmd);
	print $s2;
	    next if defined $seen{$s2};
		     ++$seen{$s2};
			      unshift @newhist, $cmd;
}

open (HIST, '>', $history) or die "cannot write $history: $!";
print HIST @newhist;
close HIST;
