#!/bin/zsh

if [[ "$#" -eq 0 ]]; then
   echo "Usage: "
   echo "idea [--wait] <filename> [--log]"
   return
fi

if [[ "$1" = "--wait" ]]; then
   shift
   WAIT=true
fi

absfile=`$SCRIPTPATH/extras/scripts/abspath $1`

echo "Runnning: "
echo ""
#echo "$IDEA_PATH/\e[31m$IDEA_VERSION\e[39m/$IDEA_POSTIFIX \e[95m$absfile"
echo " ${IDEA_PATH}bin/idea.sh \e[95m$absfile"


if [[ $2 -eq "--log" ]]; then
   `${IDEA_PATH}bin/idea.sh $absfile &` 
else
   if [[ $WAIT ]]; then
      `${IDEA_PATH}bin/idea.sh $absfile >> /dev/null 2>&1` 
   else
      `${IDEA_PATH}bin/idea.sh $absfile >> /dev/null 2>&1 &` 
   fi
fi
