#!/bin/sh

if [[ "$#" -eq 0 ]]; then
   echo "Usage:"
   echo "idea {filename} [--log]"
   return
fi

absfile=`$SCRIPTPATH/extras/scripts/abspath $1`

echo "Runnning: "
echo ""
echo "$IDEAPATH/\e[31m$IDEA_VERSION\e[39m/$IDEA_POSTIFIX \e[95m$absfile"

if [[ $2 -eq "--log" ]]; then
   `$IDEA_PATH $absfile` && 
else
   `$IDEA_PATH $absfile >> /dev/null 2>&1`  && 
fi
