#!/bin/zsh
echoMe $0

# Some of these are selected from these sources:
# 	https://github.com/cornerman/dotfiles/blob/master/zaliases

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#

#unaliases
# remove ag alias because of the conflict with silver searcher
# .oh-my-zsh/plugins/ubuntu/ubuntu.plugin.zsh
unalias ag >> /dev/null 2>&1
unalias p >> /dev/null 2>&1
# Example aliases
alias zshconfig="vim ~/.zshrc"
alias zshlocal="vim ~/zshrc.local.sh"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias ls="ls -GF --color"
alias zdoc="xdg-open /usr/share/doc/zsh/doc/zsh.pdf >> /dev/null 2>&1 &"
#alias cat="grc cat"
alias ds="du -hd 1| sort -h"
alias k="k -h"
alias hd="head -n 40 "
alias t='$HOME/Dropbox/Apps/todotxttdi/todo.sh -d $HOME/Dropbox/Apps/todotxttdi/todo.cfg'
alias todo="vim ~/Dropbox/Apps/todotxttdi/todo.txt"
# alias jq="jq '.' "
alias ex="chmod u+x "
alias idea='. $SCRIPTPATH/extras/scripts/idea'
alias ll="ls -lSahr"
alias l="/bin/ls -1"
alias v='vim '
alias vm='vim "$(fzf -m)"'
alias -s md=vim
alias s="sudo PATH=\"$PATH\" -E "
alias dq="sudo dpkg-query --listfiles"
alias iconf="code ~config/i3/config"
alias reload!='. ~/.zshrc'
alias cls='clear' # Good 'ol Clear Screen command
alias localzsh="vim ~/zshrc.local.sh"
alias dpk="grc dpkg-query --listfiles"
alias pp="s grc ps -aux|grep -v -E 'grep|vim|PATH='|grep "
alias gg="_ex '/usr/bin/geany' '&>/dev/null &' "
alias getip="curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'"

# mh is a shortcut for showing help.md in this repo
# every 34 line the text should break with --- inorder to 
# be represented as a slide
alias mh="sed '0~34 s/$/\n\n---\n\n/g' $SCRIPTPATH/help.md | mdp"
alias archive='tar -pczvf'

alias on='ping -c 1 8.8.8.8 && echo ":)" || echo ":("'
alias va="vim ~/.zaliases"
alias vv="vim ~/.vimrc"
alias vvl="vim ~/.vimrc.local"
alias vvp="vim ~/.vimrc.plugin"
alias vz="vim ~/.zshrc"
alias vzl="vim ~/.zshrc.local"
# usage: help read
alias help=run-help
alias t="~/Dropbox/Apps/todotxttdi/todo.sh -d ~/Dropbox/Apps/todotxttdi/todo.cfg"
alias w="~/Dropbox/Apps/todotxttdi/todo.sh -d ~/.config/todo.cfg"
alias lw="xdg-open http://localhost/?c=0-Notes/private\&p=log.md"
alias ap="sudo apt-get"
alias h="history|grep"
alias -g grep='grep  --color=always --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias -g ,1='2>&1 '
alias -g ,2='2>/dev/null '
alias -g ,3='&>/dev/null '

if [ -x "$(command -v trash-put)" ]; then
   alias rm=trash-put
fi

# these are mappings for frequently used folder, type for example:
#hash -d memo=~/Dropbox/Memo
hash -d MyDotFiles=$SCRIPTPATH
hash -d mydotfiles=$SCRIPTPATH
hash -d m=$SCRIPTPATH
hash -d vim=$SCRIPTPATH
hash -d download=~/Downloads
hash -d dropbox=~/Dropbox
hash -d pm=~/Dropbox/purchased-music/audible
hash -d config=~/.config
hash -d desktop=~/Desktop
hash -d git=~/git
hash -d bin=~/bin
hash -d notes=~/notes
hash -d sample=~/bin/sample
hash -d wiki=~/wiki
hash -d pictures=~/pictures
hash -d apps=/usr/share/applications
hash -d lapps=~/.local/share/applications/

# Conditional aliases
if [ -x "$(command -v exa)" ]; then
   APPS+="$APP_SEP ${bW}exa$cZ "
   alias ls="exa -F --time-style long-iso --color=always --color-scale --group-directories-first"
   alias ll="exa -lgaF --time-style long-iso --color=always --color-scale --group-directories-first"
   alias lart="exa -lgaF@ -s modified --time-style long-iso --color=always --color-scale"
else
   stackMsg "${cB}exa $cZ is not installed, using normal $cR ls $cZ"
   alias lart="grc ls -lart"
fi

# power completion / abbreviation expansion / buffer expansion
# see http://zshwiki.org/home/examples/zleiab for details
typeset -Ag abbreviations
abbreviations=(
  "Im"    "| more"
  "Ia"    "| awk"
  "Ig"    "| grep"
  "Ieg"   "| egrep"
  "Iag"   "| agrep"
  "Igr"   "| groff -s -p -t -e -Tlatin1 -mandoc"
  "Ip"    "| $PAGER"
  "Ih"    "| head"
  "Ik"    "| keep"
  "It"    "| tail"
  "Is"    "| sort"
  "Iv"    "| ${VISUAL:-${EDITOR}}"
  "Iw"    "| wc"
  "Ix"    "| xargs"
  "I1"    "2>&1"
  "I2"    "2>/dev/null"
  "I3"    "&>/dev/null"
)

magic-abbrev-expand() {
    local MATCH
    LBUFFER=${LBUFFER%%(#m)[_a-zA-Z0-9]#}
    LBUFFER+=${abbreviations[$MATCH]:-$MATCH}
    zle self-insert
}

no-magic-abbrev-expand() {
  LBUFFER+=' '
}

zle -N magic-abbrev-expand
zle -N no-magic-abbrev-expand
bindkey " " magic-abbrev-expand
bindkey "^x " no-magic-abbrev-expand
bindkey -M isearch " " self-insert
